apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: django-led
  name: django-led
  namespace: default 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-led
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: django-led
    spec:
      containers:
      - image: linuxrobotgeek/django-led:v1.0.0
        imagePullPolicy: IfNotPresent
        name: django-led
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
